/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ClientInterfaceService } from "../clientInterface.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ClientInterfaceCreateInput } from "./ClientInterfaceCreateInput";
import { ClientInterface } from "./ClientInterface";
import { ClientInterfaceFindManyArgs } from "./ClientInterfaceFindManyArgs";
import { ClientInterfaceWhereUniqueInput } from "./ClientInterfaceWhereUniqueInput";
import { ClientInterfaceUpdateInput } from "./ClientInterfaceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ClientInterfaceControllerBase {
  constructor(
    protected readonly service: ClientInterfaceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ClientInterface })
  @nestAccessControl.UseRoles({
    resource: "ClientInterface",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createClientInterface(
    @common.Body() data: ClientInterfaceCreateInput
  ): Promise<ClientInterface> {
    return await this.service.createClientInterface({
      data: {
        ...data,

        client: data.client
          ? {
              connect: data.client,
            }
          : undefined,

        interfaceField: data.interfaceField
          ? {
              connect: data.interfaceField,
            }
          : undefined,
      },
      select: {
        accessDetails: true,

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        interfaceField: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ClientInterface] })
  @ApiNestedQuery(ClientInterfaceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ClientInterface",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async clientInterfaces(
    @common.Req() request: Request
  ): Promise<ClientInterface[]> {
    const args = plainToClass(ClientInterfaceFindManyArgs, request.query);
    return this.service.clientInterfaces({
      ...args,
      select: {
        accessDetails: true,

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        interfaceField: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ClientInterface })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClientInterface",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async clientInterface(
    @common.Param() params: ClientInterfaceWhereUniqueInput
  ): Promise<ClientInterface | null> {
    const result = await this.service.clientInterface({
      where: params,
      select: {
        accessDetails: true,

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        interfaceField: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ClientInterface })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClientInterface",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateClientInterface(
    @common.Param() params: ClientInterfaceWhereUniqueInput,
    @common.Body() data: ClientInterfaceUpdateInput
  ): Promise<ClientInterface | null> {
    try {
      return await this.service.updateClientInterface({
        where: params,
        data: {
          ...data,

          client: data.client
            ? {
                connect: data.client,
              }
            : undefined,

          interfaceField: data.interfaceField
            ? {
                connect: data.interfaceField,
              }
            : undefined,
        },
        select: {
          accessDetails: true,

          client: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          interfaceField: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ClientInterface })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ClientInterface",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteClientInterface(
    @common.Param() params: ClientInterfaceWhereUniqueInput
  ): Promise<ClientInterface | null> {
    try {
      return await this.service.deleteClientInterface({
        where: params,
        select: {
          accessDetails: true,

          client: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,

          interfaceField: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
