/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ClientInterfaceCreateNestedManyWithoutClientsInput } from "./ClientInterfaceCreateNestedManyWithoutClientsInput";
import { Type } from "class-transformer";
import { ContactCreateNestedManyWithoutClientsInput } from "./ContactCreateNestedManyWithoutClientsInput";
import { RdpDetailCreateNestedManyWithoutClientsInput } from "./RdpDetailCreateNestedManyWithoutClientsInput";

@InputType()
class ClientCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => ClientInterfaceCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => ClientInterfaceCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => ClientInterfaceCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  clientInterfaces?: ClientInterfaceCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: () => ContactCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => ContactCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => ContactCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  contacts?: ContactCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  flexAccountNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => RdpDetailCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => RdpDetailCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => RdpDetailCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  rdpDetails?: RdpDetailCreateNestedManyWithoutClientsInput;
}

export { ClientCreateInput as ClientCreateInput };
